export const DISTRICTS_LIST_REQUEST = 'DISTRICTS_LIST_REQUEST'
export const DISTRICTS_LIST_SUCCESS = 'DISTRICTS_LIST_SUCCESS'
export const DISTRICTS_LIST_FAIL = 'DISTRICTS_LIST_FAIL'



export const DISTRICTS_DETAILS_REQUEST = 'DISTRICTS_DETAILS_REQUEST'
export const DISTRICTS_DETAILS_SUCCESS = 'DISTRICTS_DETAILS_SUCCESS'
export const DISTRICTS_DETAILS_FAIL = 'DISTRICTS_DETAILS_FAIL'


export const DISTRICTS_DELETE_REQUEST = 'DISTRICTS_DELETE_REQUEST'
export const DISTRICTS_DELETE_SUCCESS = 'DISTRICTS_DELETE_SUCCESS'
export const DISTRICTS_DELETE_FAIL = 'DISTRICTS_DELETE_FAIL'


export const DESTINATION_DELETE_REQUEST = 'DESTINATION_DELETE_REQUEST'
export const DESTINATION_DELETE_SUCCESS = 'DESTINATION_DELETE_SUCCESS'
export const DESTINATION_DELETE_FAIL = 'DESTINATION_DELETE_FAIL'

export const DISTRICTS_CREATE_REQUEST = 'DISTRICTS_CREATE_REQUEST'
export const DISTRICTS_CREATE_SUCCESS = 'DISTRICTS_CREATE_SUCCESS'
export const DISTRICTS_CREATE_FAIL = 'DISTRICTS_CREATE_FAIL'
export const DISTRICTS_CREATE_RESET = 'DISTRICTS_CREATE_RESET'


export const DESTINATION_CREATE_REQUEST = 'DESTINATION_CREATE_REQUEST'
export const DESTINATION_CREATE_SUCCESS = 'DESTINATION_CREATE_SUCCESS'
export const DESTINATION_CREATE_FAIL = 'DESTINATION_CREATE_FAIL'
export const DESTINATION_CREATE_RESET = 'DESTINATION_CREATE_RESET'


export const ADD_DESTINATION_REQUEST = 'ADD_DESTINATION_REQUEST'
export const ADD_DESTINATION_SUCCESS = 'ADD_DESTINATION_SUCCESS'
export const ADD_DESTINATION_FAIL = 'ADD_DESTINATION_FAIL'
export const ADD_DESTINATION_RESET = 'ADD_DESTINATION_RESET'


export const DISTRICTS_UPDATE_REQUEST = 'DISTRICTS_UPDATE_REQUEST'
export const DISTRICTS_UPDATE_SUCCESS = 'DISTRICTS_UPDATE_SUCCESS'
export const DISTRICTS_UPDATE_FAIL = 'DISTRICTS_UPDATE_FAIL'
export const DISTRICTS_UPDATE_RESET = 'DISTRICTS_UPDATE_RESET'


export const DESTINATION_UPDATE_REQUEST = 'DESTINATION_UPDATE_REQUEST'
export const DESTINATION_UPDATE_SUCCESS = 'DESTINATION_UPDATE_SUCCESS'
export const DESTINATION_UPDATE_FAIL = 'DESTINATION_UPDATE_FAIL'
export const DESTINATION_UPDATE_RESET = 'DESTINATION_UPDATE_RESET'